In [ ]:
pip install ai4bharat-transliteration

In [ ]:
pip install google-generativeai

In [ ]:
pip install transformers

In [ ]:
pip install python-dotenv

In [8]:
import pandas as pd
import re
# from ai4bharat.transliteration import XlitEngine
from dotenv import load_dotenv
load_dotenv()
import  os
# os.environ['GOOGLE_API_KEY'] = os.getenv('GOOGLE_API_KEY', '')
import pathlib
import textwrap
from IPython.display import display
from IPython.display import Markdown
import google.generativeai as genai
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM, pipeline
genai.configure(api_key = os.getenv('GOOGLE_API_KEY'))

In [145]:
f = open('/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/dataset/WhatsApp Chat with Sahithi Dad.txt','r',encoding='utf-8')

In [146]:
data = f.read()

In [148]:
data

'30/11/2023, 7:44\u202fam - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n30/11/2023, 7:45\u202fam - ysrfoundation2: Hii\n30/11/2023, 7:49\u202fam - Sahithi Dad: Hlo\n03/12/2023, 1:34\u202fpm - ysrfoundation2: Hiii\n03/12/2023, 1:52\u202fpm - ysrfoundation2: Sahithi\n03/12/2023, 1:52\u202fpm - ysrfoundation2: What are you doing\n03/12/2023, 3:39\u202fpm - Sahithi Dad: Ntg\n03/12/2023, 3:39\u202fpm - Sahithi Dad: Ra\n04/12/2023, 6:49\u202fpm - ysrfoundation2: <Media omitted>\n04/12/2023, 6:49\u202fpm - ysrfoundation2: <Media omitted>\n04/12/2023, 8:27\u202fpm - ysrfoundation2: null\n04/12/2023, 8:27\u202fpm - Sahithi Dad: null\n04/12/2023, 8:28\u202fpm - ysrfoundation2: null\n04/12/2023, 9:02\u202fpm - Sahithi Dad: Am ayna telisinda\n04/12/2023, 9:02\u202fpm - ysrfoundation2: Ledhu sir chuda lee anta\n04/12/2023, 9:02\u202fpm - Sahithi Dad: Avunaa\n04/12/2023, 9:02\u202fpm - ysrfoundation2: Hmm\n04/12/2023, 9:02\u202fpm - Sahithi Dad: Burra paadu\n04/12/2023, 9:02\u202fpm - Sahithi Dad: Asalu\n04/12/2023, 9:03\u202fpm - ysrfoundation2: Sahithi pottidi ki msg cheyu raa\n04/12/2023, 9:03\u202fpm - ysrfoundation2: Haa\n04/12/2023, 9:03\u202fpm - Sahithi Dad: Yevariki\n04/12/2023, 9:03\u202fpm - Sahithi Dad: Chellu kaa\n04/12/2023, 9:03\u202fpm - ysrfoundation2: Mi head ki\n04/12/2023, 9:03\u202fpm - ysrfoundation2: Haa\n04/12/2023, 9:03\u202fpm - Sahithi Dad: Na gubalu yegara gottey galadu le\n04/12/2023, 9:04\u202fpm - ysrfoundation2: 🤣🤣🤣\n04/12/2023, 9:04\u202fpm - ysrfoundation2: Sare tinnava\n04/12/2023, 9:04\u202fpm - Sahithi Dad: Haa\n04/12/2023, 9:04\u202fpm - Sahithi Dad: Nuvvo\n04/12/2023, 9:04\u202fpm - Sahithi Dad: Call cheyyamane vadiki\n04/12/2023, 9:04\u202fpm - Sahithi Dad: Vadhu\n04/12/2023, 9:04\u202fpm - Sahithi Dad: Le\n04/12/2023, 9:05\u202fpm - ysrfoundation2: Ledhu time chusava\n04/12/2023, 9:05\u202fpm - ysrfoundation2: Hoo\n04/12/2023, 9:05\u202fpm - Sahithi Dad: Ade chepthunna\n04/12/2023, 9:06\u202fpm - ysrfoundation2: Hmm\n04/12/2023, 9:06\u202fpm - Sahithi Dad: Ohh\n04/12/2023, 9:06\u202fpm - Sahithi Dad: Ledu ledu\n04/12/2023, 9:06\u202fpm - ysrfoundation2: Hoo\n04/12/2023, 9:06\u202fpm - ysrfoundation2: Inkante\n04/12/2023, 9:06\u202fpm - Sahithi Dad: Burra paadu\n04/12/2023, 9:06\u202fpm - Sahithi Dad: Kadupula noppi\n04/12/2023, 9:07\u202fpm - Sahithi Dad: Yeh visyam clarity ga telidhu\n04/12/2023, 9:07\u202fpm - Sahithi Dad: Chi\n04/12/2023, 9:07\u202fpm - Sahithi Dad: Am clg yeh babu\n04/12/2023, 9:07\u202fpm - Sahithi Dad: Manadu\n04/12/2023, 9:07\u202fpm - Sahithi Dad: Manadi\n04/12/2023, 9:07\u202fpm - ysrfoundation2: Haa same feeling kani chepa lenu\n04/12/2023, 9:08\u202fpm - Sahithi Dad: 😢\n04/12/2023, 9:08\u202fpm - ysrfoundation2: Sare Lee vadu reply Este niku msg chesta lee\n04/12/2023, 9:08\u202fpm - Sahithi Dad: Kk\n04/12/2023, 9:31\u202fpm - Sahithi Dad: Padmavathi clg kuda selavu\n04/12/2023, 9:32\u202fpm - ysrfoundation2: Hoo appude adige sava\n04/12/2023, 9:43\u202fpm - Sahithi Dad: Fast nenu\n04/12/2023, 9:50\u202fpm - Sahithi Dad: <Media omitted>\n04/12/2023, 9:50\u202fpm - Sahithi Dad: Selavu manaki kuda\n04/12/2023, 9:51\u202fpm - Sahithi Dad: Tomorrow (05.12.23) college holiday\n05/12/2023, 6:58\u202fam - ysrfoundation2: S\n05/12/2023, 6:58\u202fam - ysrfoundation2: Super\n05/12/2023, 3:00\u202fpm - Sahithi Dad: Am antha badha\n05/12/2023, 3:01\u202fpm - ysrfoundation2: Arey maa Chelli pettamandi petta\n05/12/2023, 3:01\u202fpm - ysrfoundation2: Niku badha ante CLG tmrw holiday estaro ledho ani\n05/12/2023, 3:02\u202fpm - Sahithi Dad: Nakaa\n05/12/2023, 3:02\u202fpm - ysrfoundation2: Ledhu naku ani pettali kani mistake\n05/12/2023, 3:06\u202fpm - Sahithi Dad: Ohh\n05/12/2023, 3:06\u202fpm - Sahithi Dad: Me chelli ki echara\n05/12/2023, 3:06\u202fpm - Sahithi Dad: Selavu\n05/12/2023, 3:06\u202fpm - ysrfoundation2: Haa\n05/12/2023, 9:21\u202fpm - Sahithi Dad: Hi\n05/12/2023, 9:22\u202fpm - Sahithi Dad: Chadivesava\n05/12/2023, 9:22\u202fpm - ysrfoundation2: Ledhu\n05/12/2023, 9:22\u202fpm - ysrfoundation2: Tmrw holiday estaro amo ani balance uncha\n05/12/2023, 9:23\u202fpm - Sahithi Dad: Evvaru mari\n05/12/2023, 9:23\u202fpm - ysrfoundation2: Hoo sare evvaku pothe ledhu\n05/12/2023, 9:24\u202fpm - ysrfoundation2: Ante\n05/12/2023, 9:24\u202fpm - Sahithi Dad: Jyothi akka vallu bojanam ki pilichara meku\n05/12/2023, 9:25\u202fpm - ysrfoundation2: Epudu\n05/12/2023, 9:25\u202fpm - Sahithi Dad: Repu\n05/12/2023, 9:25\u202fpm - ysrfoundation2: Emo naku telidhu\n05/12/2023, 9:25\u202fpm - Sahithi Dad: Me mummy ki adigi cheppu\n05/12/2023, 9:25\u202fpm - ysrfoundation2: Sare kani\n05/12/2023, 9:26\u202fpm - ysrfoundation2: Nuvvu chadesava\n05/12/2023, 9:26\u202fpm - Sahithi Dad: Ledu ra\n05/12/2023, 9:26\u202fpm - Sahithi Dad: Bayam vesthundi\n05/12/2023, 9:26\u202fpm - Sahithi Dad: Naku\n05/12/2023, 9:27\u202fpm - ysrfoundation2: Hoo\n05/12/2023, 9:30\u202fpm - Sahithi Dad: Haaa\n06/12/2023, 7:00\u202fam - Sahithi Dad: Send me\n06/12/2023, 7:00\u202fam - ysrfoundation2: <Media omitted>\n06/12/2023, 7:01\u202fam - Sahithi Dad: Today\n06/12/2023, 7:01\u202fam - Sahithi Dad: Holiday\n06/12/2023, 7:01\u202fam - Sahithi Dad: Msg chudu grouplo\n06/12/2023, 7:11\u202fam - ysrfoundation2: Hoo super raa\n06/12/2023, 8:07\u202fam - Sahithi Dad: Orey\n06/12/2023, 8:07\u202fam - Sahithi Dad: Bojanalaki vasthava\n06/12/2023, 1:58\u202fpm - Sahithi Dad: Shake\n06/12/2023, 2:07\u202fpm - ysrfoundation2: Hiii\n06/12/2023, 2:07\u202fpm - ysrfoundation2: Tinnava\n06/12/2023, 8:17\u202fpm - Sahithi Dad: Hi\n06/12/2023, 8:17\u202fpm - ysrfoundation2: Hiii\n06/12/2023, 8:17\u202fpm - Sahithi Dad: Hlo\n06/12/2023, 8:46\u202fpm - Sahithi Dad: Aishu\n06/12/2023, 8:58\u202fpm - Sahithi Dad: 💯\n06/12/2023, 9:27\u202fpm - ysrfoundation2: 😍😍\n08/12/2023, 6:55\u202fpm - ysrfoundation2: <Media omitted>\n08/12/2023, 6:55\u202fpm - ysrfoundation2: <Media omitted>\n08/12/2023, 6:55\u202fpm - ysrfoundation2: <Media omitted>\n08/12/2023, 6:55\u202fpm - ysrfoundation2: <Media omitted>\n08/12/2023, 6:55\u202fpm - ysrfoundation2: <Media omitted>\n08/12/2023, 8:35\u202fpm - Sahithi Dad: Nice\n08/12/2023, 9:09\u202fpm - ysrfoundation2: 😚😚\n10/12/2023, 5:27\u202fpm - ysrfoundation2: <Media omitted>\n10/12/2023, 5:33\u202fpm - ysrfoundation2: Shop now on Meesho! \nhttps://www.meesho.com/s/p/4w7qta?utm_source=s_w\n10/12/2023, 6:27\u202fpm - Sahithi Dad: <Media omitted>\n10/12/2023, 6:36\u202fpm - Sahithi Dad: <Media omitted>\n11/12/2023, 7:19\u202fpm - ysrfoundation2: <Media omitted>\n11/12/2023, 7:31\u202fpm - ysrfoundation2: https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz\n11/12/2023, 7:35\u202fpm - ysrfoundation2: Arey EDI oka sari chudu\n11/12/2023, 8:47\u202fpm - Sahithi Dad: Ila vuntundi aa\n11/12/2023, 8:50\u202fpm - ysrfoundation2: Haa\n11/12/2023, 8:50\u202fpm - ysrfoundation2: Epudu Mari pondi\n11/12/2023, 8:53\u202fpm - Sahithi Dad: Enti\n11/12/2023, 8:53\u202fpm - Sahithi Dad: Pondi enti ra\n11/12/2023, 8:54\u202fpm - ysrfoundation2: Epudu Mari poindhi  raa\n11/12/2023, 8:57\u202fpm - Sahithi Dad: Baledu antunnava\n11/12/2023, 8:57\u202fpm - Sahithi Dad: Ma intlo chala long antunnaru\n11/12/2023, 8:57\u202fpm - ysrfoundation2: Ledhu raa super ga chesaru antunna\n11/12/2023, 8:57\u202fpm - ysrfoundation2: Hoo\n11/12/2023, 8:58\u202fpm - Sahithi Dad: Avunu\n11/12/2023, 8:58\u202fpm - ysrfoundation2: Emo time undi kadha chudam\n11/12/2023, 8:58\u202fpm - Sahithi Dad: Haa sare le\n11/12/2023, 8:58\u202fpm - ysrfoundation2: Hmm\n11/12/2023, 9:16\u202fpm - ysrfoundation2: Arey balloons ne phone lo order cheyu raa\n11/12/2023, 9:16\u202fpm - ysrfoundation2: Epudu cheste aapudo vastadi\n11/12/2023, 9:42\u202fpm - Sahithi Dad: Na phone lo nenu yeppudu pettaledu ra\n11/12/2023, 9:42\u202fpm - Sahithi Dad: Ne phone lo petti money kavalante echestha\n12/12/2023, 7:31\u202fpm - Sahithi Dad: Aishu ma nanna money adigaru ra\n12/12/2023, 7:39\u202fpm - ysrfoundation2: Arey 350 ani chepamannadi taruvata chudam annadu\n12/12/2023, 7:39\u202fpm - ysrfoundation2: Ok na\n12/12/2023, 7:41\u202fpm - Sahithi Dad: Yevaru\n12/12/2023, 7:41\u202fpm - ysrfoundation2: Ma mom\n12/12/2023, 7:42\u202fpm - Sahithi Dad: Adi kaadu yeh babu\n12/12/2023, 7:42\u202fpm - ysrfoundation2: Mari enti\n12/12/2023, 7:42\u202fpm - Sahithi Dad: Cheppuluvi, kit vi\n12/12/2023, 7:43\u202fpm - ysrfoundation2: Enti ardham kaledhu\n12/12/2023, 7:45\u202fpm - ysrfoundation2: Phone cheyyala\n12/12/2023, 7:45\u202fpm - Sahithi Dad: Cheppulu\n12/12/2023, 7:45\u202fpm - Sahithi Dad: Baby kit usha valla babu ki teesukunnam kada\n12/12/2023, 7:45\u202fpm - Sahithi Dad: Aa money\n12/12/2023, 7:46\u202fpm - ysrfoundation2: Haa sare\n12/12/2023, 7:46\u202fpm - Sahithi Dad: Nenu raanu ra\n12/12/2023, 7:46\u202fpm - ysrfoundation2: Em\n12/12/2023, 7:47\u202fpm - Sahithi Dad: Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru\n12/12/2023, 7:47\u202fpm - ysrfoundation2: Hoo\n12/12/2023, 7:47\u202fpm - Sahithi Dad: Haaa\n12/12/2023, 7:47\u202fpm - ysrfoundation2: Sare kani money anta\n12/12/2023, 7:48\u202fpm - Sahithi Dad: 280 ra\n12/12/2023, 7:48\u202fpm - Sahithi Dad: Monna 50 icha annav kada\n12/12/2023, 7:48\u202fpm - Sahithi Dad: 230\n12/12/2023, 7:48\u202fpm - ysrfoundation2: Haa kk\n12/12/2023, 7:48\u202fpm - Sahithi Dad: Haa sare\n13/12/2023, 8:07\u202fam - Sahithi Dad: 🙏🏻\n13/12/2023, 8:07\u202fam - Sahithi Dad: Y\n13/12/2023, 8:07\u202fam - ysrfoundation2: Song baledha\n13/12/2023, 8:08\u202fam - Sahithi Dad: Super\n13/12/2023, 8:08\u202fam - ysrfoundation2: Anduke petta reasons em ledhu\n16/12/2023, 8:19\u202fam - Sahithi Dad: Aishu pettava photo\n16/12/2023, 5:45\u202fpm - ysrfoundation2: <Media omitted>\n16/12/2023, 8:06\u202fpm - Sahithi Dad: Enti ra\n16/12/2023, 8:41\u202fpm - ysrfoundation2: Hii sahithi\n16/12/2023, 8:42\u202fpm - Sahithi Dad: Hi ra\n16/12/2023, 8:42\u202fpm - Sahithi Dad: Photo pettava\n16/12/2023, 8:42\u202fpm - ysrfoundation2: Haa pedata lee\n16/12/2023, 8:43\u202fpm - Sahithi Dad: Sry raledu endhuku ante dress change cheyledu\n16/12/2023, 8:43\u202fpm - Sahithi Dad: Andhuke\n16/12/2023, 8:43\u202fpm - ysrfoundation2: Paravaledu lee\n16/12/2023, 8:43\u202fpm - ysrfoundation2: Akhila kavi vacharu\n16/12/2023, 8:43\u202fpm - Sahithi Dad: Marchipoku e roju pettu\n16/12/2023, 8:43\u202fpm - Sahithi Dad: Avunaa\n16/12/2023, 8:43\u202fpm - ysrfoundation2: Haa\n16/12/2023, 8:43\u202fpm - Sahithi Dad: Videos pettu\n16/12/2023, 8:43\u202fpm - Sahithi Dad: Naku\n16/12/2023, 8:44\u202fpm - Sahithi Dad: Puja vi\n16/12/2023, 8:44\u202fpm - ysrfoundation2: Haa\n16/12/2023, 8:44\u202fpm - ysrfoundation2: <Media omitted>\n16/12/2023, 8:44\u202fpm - ysrfoundation2: <Media omitted>\n16/12/2023, 8:44\u202fpm - ysrfoundation2: <Media omitted>\n16/12/2023, 8:44\u202fpm - ysrfoundation2: <Media omitted>\n16/12/2023, 8:44\u202fpm - ysrfoundation2: <Media omitted>\n16/12/2023, 8:44\u202fpm - ysrfoundation2: <Media omitted>\n17/12/2023, 6:21\u202fpm - Sahithi Dad: Aishu pettava\n17/12/2023, 6:21\u202fpm - Sahithi Dad: Photo\n17/12/2023, 7:05\u202fpm - ysrfoundation2: Haa\n17/12/2023, 9:00\u202fpm - Sahithi Dad: Am annaru\n18/12/2023, 9:36\u202fpm - Sahithi Dad: Oley hd vi pettamani cheppa kadey\n18/12/2023, 9:36\u202fpm - Sahithi Dad: 🫢\n19/12/2023, 8:10\u202fpm - Sahithi Dad: Hi\n19/12/2023, 8:14\u202fpm - ysrfoundation2: Hii\n19/12/2023, 8:57\u202fpm - Sahithi Dad: Chadivesava madam\n19/12/2023, 9:14\u202fpm - ysrfoundation2: Ledhu raa maths main chudali\n19/12/2023, 9:19\u202fpm - Sahithi Dad: Chusava mari\n21/12/2023, 7:20\u202fpm - ysrfoundation2: <Media omitted>\n21/12/2023, 7:20\u202fpm - ysrfoundation2: <Media omitted>\n21/12/2023, 7:20\u202fpm - ysrfoundation2: You deleted this message\n21/12/2023, 8:01\u202fpm - ysrfoundation2: <Media omitted>\n21/12/2023, 8:41\u202fpm - ysrfoundation2: <Media omitted>\n21/12/2023, 8:45\u202fpm - Sahithi Dad: Chadivesava\n21/12/2023, 9:12\u202fpm - ysrfoundation2: Ledhu\n21/12/2023, 9:14\u202fpm - Sahithi Dad: Nv brilliant le appudu kappudu ayna chusi rasesthav\n21/12/2023, 9:16\u202fpm - ysrfoundation2: Haa avunu lee\n21/12/2023, 9:33\u202fpm - Sahithi Dad: Yes its true\n22/12/2023, 7:32\u202fam - Sahithi Dad: Aishu e question chadivava\n22/12/2023, 7:32\u202fam - ysrfoundation2: Nanu asalu em chadavale\n22/12/2023, 7:33\u202fam - Sahithi Dad: Avunaa\n22/12/2023, 7:33\u202fam - Sahithi Dad: Sare le\n22/12/2023, 7:33\u202fam - ysrfoundation2: Hmm\n22/12/2023, 7:51\u202fpm - Sahithi Dad: Send me\n22/12/2023, 7:51\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 8:02\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 8:02\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 8:40\u202fpm - Sahithi Dad: Aishu\n22/12/2023, 8:59\u202fpm - Sahithi Dad: Adigava\n22/12/2023, 8:59\u202fpm - Sahithi Dad: Vallaki  am annaru\n22/12/2023, 9:04\u202fpm - ysrfoundation2: Avariki\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:10\u202fpm - ysrfoundation2: <Media omitted>\n22/12/2023, 9:14\u202fpm - Sahithi Dad: Anu monika mani vallaki\n22/12/2023, 9:23\u202fpm - ysrfoundation2: Haa kk moni , rama\n22/12/2023, 9:23\u202fpm - ysrfoundation2: Anu kudha m avvaka pote  annadi\n22/12/2023, 9:37\u202fpm - ysrfoundation2: Hii\n22/12/2023, 9:45\u202fpm - Sahithi Dad: Hii\n23/12/2023, 8:00\u202fam - Sahithi Dad: Hi\n23/12/2023, 8:04\u202fam - ysrfoundation2: Hiii\n23/12/2023, 8:19\u202fam - Sahithi Dad: Am doing\n23/12/2023, 9:04\u202fpm - ysrfoundation2: Hiii\n23/12/2023, 9:08\u202fpm - Sahithi Dad: Hi\n23/12/2023, 9:09\u202fpm - ysrfoundation2: Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa\n23/12/2023, 9:11\u202fpm - Sahithi Dad: Rama raadhu aa\n23/12/2023, 9:12\u202fpm - ysrfoundation2: Ante mrng varuku telidhu\n23/12/2023, 9:13\u202fpm - Sahithi Dad: Am alaga\n23/12/2023, 9:13\u202fpm - ysrfoundation2: Emo\n23/12/2023, 9:13\u202fpm - Sahithi Dad: Avuna\n23/12/2023, 9:13\u202fpm - ysrfoundation2: Hmm\n23/12/2023, 9:14\u202fpm - Sahithi Dad: Inko 4members yevaru ra\n23/12/2023, 9:14\u202fpm - ysrfoundation2: Chinnamudu , paiga vallu avaro anta family nee\n23/12/2023, 9:15\u202fpm - Sahithi Dad: Ohh kk le\n23/12/2023, 9:15\u202fpm - ysrfoundation2: Hmm\n23/12/2023, 9:15\u202fpm - ysrfoundation2: Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali\n23/12/2023, 9:16\u202fpm - Sahithi Dad: Sare\n23/12/2023, 9:17\u202fpm - ysrfoundation2: Sare inka\n23/12/2023, 9:18\u202fpm - Sahithi Dad: Cheppali\n23/12/2023, 9:18\u202fpm - ysrfoundation2: Ante tmrw kosam adaina cheppu\n23/12/2023, 9:19\u202fpm - Sahithi Dad: Games aa\n23/12/2023, 9:19\u202fpm - ysrfoundation2: Haa\n23/12/2023, 9:20\u202fpm - Sahithi Dad: Okka 5min aaagu\n23/12/2023, 9:20\u202fpm - Sahithi Dad: Msg chesthanu\n23/12/2023, 9:20\u202fpm - ysrfoundation2: Kk\n23/12/2023, 9:20\u202fpm - Sahithi Dad: Yeh dress vesthav\n23/12/2023, 9:21\u202fpm - ysrfoundation2: Nenu birthday di anukuntunna u\n23/12/2023, 9:23\u202fpm - Sahithi Dad: Avunaa\n23/12/2023, 9:23\u202fpm - ysrfoundation2: Hmm\n23/12/2023, 9:23\u202fpm - Sahithi Dad: Mari nenu am veyyali\n23/12/2023, 9:23\u202fpm - Sahithi Dad: Authe\n23/12/2023, 9:24\u202fpm - ysrfoundation2: Emo nuvve Alo chinchu\n23/12/2023, 9:24\u202fpm - Sahithi Dad: Cheppu nuvvu\n23/12/2023, 9:24\u202fpm - ysrfoundation2: Naku ala telustunndi\n23/12/2023, 9:25\u202fpm - Sahithi Dad: Na dresslu anni chusav kada\n23/12/2023, 9:25\u202fpm - ysrfoundation2: Emo raa nuvve decide avvu\n23/12/2023, 9:25\u202fpm - Sahithi Dad: Sare le\n23/12/2023, 9:26\u202fpm - Sahithi Dad: <Media omitted>\n23/12/2023, 9:26\u202fpm - Sahithi Dad: Edi ok naa\n23/12/2023, 9:26\u202fpm - ysrfoundation2: Haa kk\n23/12/2023, 9:27\u202fpm - Sahithi Dad: Kk le\n23/12/2023, 9:28\u202fpm - ysrfoundation2: Hmm\n23/12/2023, 9:28\u202fpm - Sahithi Dad: Leka pothe inko top vundi\n23/12/2023, 9:28\u202fpm - ysrfoundation2: Ado\n23/12/2023, 9:28\u202fpm - Sahithi Dad: Kothadi adi ayna vadesthanu le\n23/12/2023, 9:28\u202fpm - ysrfoundation2: Haa ne estam nee dress\n23/12/2023, 9:28\u202fpm - Sahithi Dad: Sare le\n23/12/2023, 9:29\u202fpm - ysrfoundation2: Hmm\n23/12/2023, 9:29\u202fpm - Sahithi Dad: Inkem games adugu mani vallaki\n24/12/2023, 7:03\u202fam - ysrfoundation2: Hiii sahi\n24/12/2023, 7:03\u202fam - ysrfoundation2: Anu ki phone cheyu oka sari adugu\n24/12/2023, 7:24\u202fam - Sahithi Dad: Sare\n24/12/2023, 8:38\u202fam - Sahithi Dad: Hi\n24/12/2023, 8:39\u202fam - Sahithi Dad: Enni gantalaki ra\n24/12/2023, 8:45\u202fam - Sahithi Dad: Aishu phone pay number pettu money phone pay chestha\n24/12/2023, 8:45\u202fam - Sahithi Dad: null\n24/12/2023, 9:01\u202fam - ysrfoundation2: 9949437849\n24/12/2023, 9:01\u202fam - ysrfoundation2: Kk naa\n24/12/2023, 9:02\u202fam - Sahithi Dad: Kk\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:43\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 5:51\u202fpm - ysrfoundation2: <Media omitted>\n24/12/2023, 8:30\u202fpm - Sahithi Dad: Orey phone pay maadi avvatledu limit aypoyindi madi e roju 

In [149]:
pattern = "\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s" #24 hr pattern
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s[APMapm]{2}\s-\s' #12 hr pattern

In [150]:
messages = re.split(pattern,data)[1:]
dates = re.findall(pattern,data)
df = pd.DataFrame({'user_message':messages, 'message_date':dates})

In [151]:
messages

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 'ysrfoundation2: Hii\n',
 'Sahithi Dad: Hlo\n',
 'ysrfoundation2: Hiii\n',
 'ysrfoundation2: Sahithi\n',
 'ysrfoundation2: What are you doing\n',
 'Sahithi Dad: Ntg\n',
 'Sahithi Dad: Ra\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: null\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: null\n',
 'Sahithi Dad: Am ayna telisinda\n',
 'ysrfoundation2: Ledhu sir chuda lee anta\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Burra paadu\n',
 'Sahithi Dad: Asalu\n',
 'ysrfoundation2: Sahithi pottidi ki msg cheyu raa\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Yevariki\n',
 'Sahithi Dad: Chellu kaa\n',
 'ysrfoundation2: Mi head ki\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Na gubalu yegara gottey galadu le\n',
 'ysrfoundation2: 🤣🤣🤣\n',
 'ysrfoundation2: Sare tinnava\n',
 'Sahithi Dad: Haa\n',
 'Sahithi Dad: Nuvvo\n',
 'Sahithi Dad: Call cheyyamane vadiki\n',
 'Sahithi Dad: Vadhu\n',
 'Sahithi Dad: Le\n',
 'ysrfoundation2: Ledhu time chusava\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Ade chepthunna\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Ohh\n',
 'Sahithi Dad: Ledu ledu\n',
 'ysrfoundation2: Hoo\n',
 'ysrfoundation2: Inkante\n',
 'Sahithi Dad: Burra paadu\n',
 'Sahithi Dad: Kadupula noppi\n',
 'Sahithi Dad: Yeh visyam clarity ga telidhu\n',
 'Sahithi Dad: Chi\n',
 'Sahithi Dad: Am clg yeh babu\n',
 'Sahithi Dad: Manadu\n',
 'Sahithi Dad: Manadi\n',
 'ysrfoundation2: Haa same feeling kani chepa lenu\n',
 'Sahithi Dad: 😢\n',
 'ysrfoundation2: Sare Lee vadu reply Este niku msg chesta lee\n',
 'Sahithi Dad: Kk\n',
 'Sahithi Dad: Padmavathi clg kuda selavu\n',
 'ysrfoundation2: Hoo appude adige sava\n',
 'Sahithi Dad: Fast nenu\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Selavu manaki kuda\n',
 'Sahithi Dad: Tomorrow (05.12.23) college holiday\n',
 'ysrfoundation2: S\n',
 'ysrfoundation2: Super\n',
 'Sahithi Dad: Am antha badha\n',
 'ysrfoundation2: Arey maa Chelli pettamandi petta\n',
 'ysrfoundation2: Niku badha ante CLG tmrw holiday estaro ledho ani\n',
 'Sahithi Dad: Nakaa\n',
 'ysrfoundation2: Ledhu naku ani pettali kani mistake\n',
 'Sahithi Dad: Ohh\n',
 'Sahithi Dad: Me chelli ki echara\n',
 'Sahithi Dad: Selavu\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Hi\n',
 'Sahithi Dad: Chadivesava\n',
 'ysrfoundation2: Ledhu\n',
 'ysrfoundation2: Tmrw holiday estaro amo ani balance uncha\n',
 'Sahithi Dad: Evvaru mari\n',
 'ysrfoundation2: Hoo sare evvaku pothe ledhu\n',
 'ysrfoundation2: Ante\n',
 'Sahithi Dad: Jyothi akka vallu bojanam ki pilichara meku\n',
 'ysrfoundation2: Epudu\n',
 'Sahithi Dad: Repu\n',
 'ysrfoundation2: Emo naku telidhu\n',
 'Sahithi Dad: Me mummy ki adigi cheppu\n',
 'ysrfoundation2: Sare kani\n',
 'ysrfoundation2: Nuvvu chadesava\n',
 'Sahithi Dad: Ledu ra\n',
 'Sahithi Dad: Bayam vesthundi\n',
 'Sahithi Dad: Naku\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Haaa\n',
 'Sahithi Dad: Send me\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Today\n',
 'Sahithi Dad: Holiday\n',
 'Sahithi Dad: Msg chudu grouplo\n',
 'ysrfoundation2: Hoo super raa\n',
 'Sahithi Dad: Orey\n',
 'Sahithi Dad: Bojanalaki vasthava\n',
 'Sahithi Dad: Shake\n',
 'ysrfoundation2: Hiii\n',
 'ysrfoundation2: Tinnava\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: Hlo\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: 💯\n',
 'ysrfoundation2: 😍😍\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Nice\n',
 'ysrfoundation2: 😚😚\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Shop now on Meesho! \nhttps://www.meesho.com/s/p/4w7qta?utm_source=s_w\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz\n',
 'ysrfoundation2: Arey EDI oka sari chudu\n',
 'Sahithi Dad: Ila vuntundi aa\n',
 'ysrfoundation2: Haa\n',
 'ysrfoundation2: Epudu Mari pondi\n',
 'Sahithi Dad: Enti\n',
 'Sahithi Dad: Pondi enti ra\n',
 'ysrfoundation2: Epudu Mari poindhi  raa\n',
 'Sahithi Dad: Baledu antunnava\n',
 'Sahithi Dad: Ma intlo chala long antunnaru\n',
 'ysrfoundation2: Ledhu raa super ga chesaru antunna\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Avunu\n',
 'ysrfoundation2: Emo time undi kadha chudam\n',
 'Sahithi Dad: Haa sare le\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Arey balloons ne phone lo order cheyu raa\n',
 'ysrfoundation2: Epudu cheste aapudo vastadi\n',
 'Sahithi Dad: Na phone lo nenu yeppudu pettaledu ra\n',
 'Sahithi Dad: Ne phone lo petti money kavalante echestha\n',
 'Sahithi Dad: Aishu ma nanna money adigaru ra\n',
 'ysrfoundation2: Arey 350 ani chepamannadi taruvata chudam annadu\n',
 'ysrfoundation2: Ok na\n',
 'Sahithi Dad: Yevaru\n',
 'ysrfoundation2: Ma mom\n',
 'Sahithi Dad: Adi kaadu yeh babu\n',
 'ysrfoundation2: Mari enti\n',
 'Sahithi Dad: Cheppuluvi, kit vi\n',
 'ysrfoundation2: Enti ardham kaledhu\n',
 'ysrfoundation2: Phone cheyyala\n',
 'Sahithi Dad: Cheppulu\n',
 'Sahithi Dad: Baby kit usha valla babu ki teesukunnam kada\n',
 'Sahithi Dad: Aa money\n',
 'ysrfoundation2: Haa sare\n',
 'Sahithi Dad: Nenu raanu ra\n',
 'ysrfoundation2: Em\n',
 'Sahithi Dad: Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru\n',
 'ysrfoundation2: Hoo\n',
 'Sahithi Dad: Haaa\n',
 'ysrfoundation2: Sare kani money anta\n',
 'Sahithi Dad: 280 ra\n',
 'Sahithi Dad: Monna 50 icha annav kada\n',
 'Sahithi Dad: 230\n',
 'ysrfoundation2: Haa kk\n',
 'Sahithi Dad: Haa sare\n',
 'Sahithi Dad: 🙏🏻\n',
 'Sahithi Dad: Y\n',
 'ysrfoundation2: Song baledha\n',
 'Sahithi Dad: Super\n',
 'ysrfoundation2: Anduke petta reasons em ledhu\n',
 'Sahithi Dad: Aishu pettava photo\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Enti ra\n',
 'ysrfoundation2: Hii sahithi\n',
 'Sahithi Dad: Hi ra\n',
 'Sahithi Dad: Photo pettava\n',
 'ysrfoundation2: Haa pedata lee\n',
 'Sahithi Dad: Sry raledu endhuku ante dress change cheyledu\n',
 'Sahithi Dad: Andhuke\n',
 'ysrfoundation2: Paravaledu lee\n',
 'ysrfoundation2: Akhila kavi vacharu\n',
 'Sahithi Dad: Marchipoku e roju pettu\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Videos pettu\n',
 'Sahithi Dad: Naku\n',
 'Sahithi Dad: Puja vi\n',
 'ysrfoundation2: Haa\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Aishu pettava\n',
 'Sahithi Dad: Photo\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Am annaru\n',
 'Sahithi Dad: Oley hd vi pettamani cheppa kadey\n',
 'Sahithi Dad: 🫢\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hii\n',
 'Sahithi Dad: Chadivesava madam\n',
 'ysrfoundation2: Ledhu raa maths main chudali\n',
 'Sahithi Dad: Chusava mari\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: You deleted this message\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Chadivesava\n',
 'ysrfoundation2: Ledhu\n',
 'Sahithi Dad: Nv brilliant le appudu kappudu ayna chusi rasesthav\n',
 'ysrfoundation2: Haa avunu lee\n',
 'Sahithi Dad: Yes its true\n',
 'Sahithi Dad: Aishu e question chadivava\n',
 'ysrfoundation2: Nanu asalu em chadavale\n',
 'Sahithi Dad: Avunaa\n',
 'Sahithi Dad: Sare le\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Send me\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Adigava\n',
 'Sahithi Dad: Vallaki  am annaru\n',
 'ysrfoundation2: Avariki\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Anu monika mani vallaki\n',
 'ysrfoundation2: Haa kk moni , rama\n',
 'ysrfoundation2: Anu kudha m avvaka pote  annadi\n',
 'ysrfoundation2: Hii\n',
 'Sahithi Dad: Hii\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: Am doing\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa\n',
 'Sahithi Dad: Rama raadhu aa\n',
 'ysrfoundation2: Ante mrng varuku telidhu\n',
 'Sahithi Dad: Am alaga\n',
 'ysrfoundation2: Emo\n',
 'Sahithi Dad: Avuna\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Inko 4members yevaru ra\n',
 'ysrfoundation2: Chinnamudu , paiga vallu avaro anta family nee\n',
 'Sahithi Dad: Ohh kk le\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali\n',
 'Sahithi Dad: Sare\n',
 'ysrfoundation2: Sare inka\n',
 'Sahithi Dad: Cheppali\n',
 'ysrfoundation2: Ante tmrw kosam adaina cheppu\n',
 'Sahithi Dad: Games aa\n',
 'ysrfoundation2: Haa\n',
 'Sahithi Dad: Okka 5min aaagu\n',
 'Sahithi Dad: Msg chesthanu\n',
 'ysrfoundation2: Kk\n',
 'Sahithi Dad: Yeh dress vesthav\n',
 'ysrfoundation2: Nenu birthday di anukuntunna u\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Mari nenu am veyyali\n',
 'Sahithi Dad: Authe\n',
 'ysrfoundation2: Emo nuvve Alo chinchu\n',
 'Sahithi Dad: Cheppu nuvvu\n',
 'ysrfoundation2: Naku ala telustunndi\n',
 'Sahithi Dad: Na dresslu anni chusav kada\n',
 'ysrfoundation2: Emo raa nuvve decide avvu\n',
 'Sahithi Dad: Sare le\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Edi ok naa\n',
 'ysrfoundation2: Haa kk\n',
 'Sahithi Dad: Kk le\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Leka pothe inko top vundi\n',
 'ysrfoundation2: Ado\n',
 'Sahithi Dad: Kothadi adi ayna vadesthanu le\n',
 'ysrfoundation2: Haa ne estam nee dress\n',
 'Sahithi Dad: Sare le\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Inkem games adugu mani vallaki\n',
 'ysrfoundation2: Hiii sahi\n',
 'ysrfoundation2: Anu ki phone cheyu oka sari adugu\n',
 'Sahithi Dad: Sare\n',
 'Sahithi Dad: Hi\n',
 'Sahithi Dad: Enni gantalaki ra\n',
 'Sahithi Dad: Aishu phone pay number pettu money phone pay chestha\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: 9949437849\n',
 'ysrfoundation2: Kk naa\n',
 'Sahithi Dad: Kk\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Orey phone pay maadi avvatledu limit aypoyindi madi e roju di\n',
 'Sahithi Dad: Mrng thechi echesthanu me daddy ki cheppu\n',
 'ysrfoundation2: Kk\n',
 'Sahithi Dad: Evena pics mari levaa\n',
 'ysrfoundation2: Haa rassu ki cheppa\n',
 'ysrfoundation2: Tana daggara konni vunnay\n',
 'ysrfoundation2: Oka sari nuvvu msg pettu\n',
 'Sahithi Dad: Kk\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Hi\n',
 'ysrfoundation2: Hiii\n',
 'Sahithi Dad: https://www.instagram.com/reel/C1J_HW6pjTb/?igsh=N2ZiNzVhMjY2OA==\n',
 'ysrfoundation2: 🤣🤣\n',
 'Sahithi Dad: 😂\n',
 'Sahithi Dad: Date chusava\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Sahithi nee English key nadaggara vundi\n',
 'Sahithi Dad: Ade vethika\n',
 'Sahithi Dad: Chala sepu\n',
 'ysrfoundation2: Hoo nenu epudo msg petta\n',
 'Sahithi Dad: Mobile vundadu ani telusu gaa neku\n',
 'Sahithi Dad: 12th answer pettava\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Tqqq❤️😘🥰\n',
 'ysrfoundation2: Abho chalu lee\n',
 'Sahithi Dad: 😄\n',
 'Sahithi Dad: Open chesava\n',
 'Sahithi Dad: Set\n',
 'ysrfoundation2: Haa chusa\n',
 'ysrfoundation2: Pump evvale ante\n',
 'ysrfoundation2: Anni kk\n',
 'Sahithi Dad: Evvaleda pump\n',
 'ysrfoundation2: Ledhu\n',
 'Sahithi Dad: Kkk\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: https://youtube.com/shorts/Ze8DjY_4kVQ?si=CXBIMqJh3p7cPOzm\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Photo pettu\n',
 'ysrfoundation2: Aa photo\n',
 'Sahithi Dad: Frame\n',
 'ysrfoundation2: Pack chesadhu vadu\n',
 'Sahithi Dad: Avuna\n',
 'Sahithi Dad: Nv kuda chudaledha\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Ledhu\n',
 'Sahithi Dad: Indhaka yekkadiki vellav\n',
 'Sahithi Dad: Gift kosam aa\n',
 'ysrfoundation2: Sorry wrong answer pakodi kosam\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Gift konta annav\n',
 'ysrfoundation2: Haa tmrw suprise miku ,anu ki kudha\n',
 'Sahithi Dad: Nku cheppu le\n',
 'Sahithi Dad: Parledu\n',
 'ysrfoundation2: Tmrw chustav kadha\n',
 'Sahithi Dad: Cheppu\n',
 'Sahithi Dad: Ra\n',
 'ysrfoundation2: Bye muggulu chustunna\n',
 'Sahithi Dad: Cheppava\n',
 'Sahithi Dad: Anthe n\n',
 'Sahithi Dad: Nenu neku telisinatte chesa ga yedi chesinaa\n',
 'Sahithi Dad: Edi cheating asalu\n',
 'ysrfoundation2: Ledhu raa inka em konalo decide avvale anduke\n',
 'Sahithi Dad: Avunaa\n',
 'ysrfoundation2: Hmm\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: Aishu chude yelaga chesado\n',
 'Sahithi Dad: Chala kopam ga vundi vaadi medha\n',
 'ysrfoundation2: Haa delete kudha cheya lee\n',
 'Sahithi Dad: Cheyyadu vaadu nku telusu\n',
 'ysrfoundation2: Haa Mari em chestam nenu , nuvvu kudha chudale\n',
 'ysrfoundation2: Hmm\n',
 'ysrfoundation2: Arey cake kosam money enta\n',
 'ysrfoundation2: Cheppa lee\n',
 'ysrfoundation2: Sare anu status chusava\n',
 'Sahithi Dad: Me estham yeh\n',
 'Sahithi Dad: Vaadu inka delete cheyleda\n',
 'Sahithi Dad: Naku chala chiraku ga vundi\n',
 'Sahithi Dad: Anu kuda status pettisindi\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Vinu\n',
 'Sahithi Dad: Aishu\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: Tmrw chemistry bullet evvu\n',
 'Sahithi Dad: null\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: https://www.instagram.com/reel/C1i2zXhp-En/?igsh=MWp4bDQ1MmhxemtyOQ==\n',
 'Sahithi Dad: <Media omitted>\n',
 'ysrfoundation2: Arey msg cheyu tanuja ki\n',
 'ysrfoundation2: Plss\n',
 'Sahithi Dad: Kk\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Arey manam Ela nee epudaina photos tesukundam kk naa\n',
 'Sahithi Dad: Done done 👍👍👍\n',
 'ysrfoundation2: Sare chemistry photos pettu\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: <Media omitted>\n',
 'Sahithi Dad: Ammo chadivedham ane\n',
 'ysrfoundation2: Haa kani epudu di ee paper\n',
 'Sahithi Dad: Repatiki\n',
 'ysrfoundation2: <Media omitted>\n',
 'Sahithi Dad: Hiiii\n',
 'Sahithi Dad: Hi\n',
 'Sahithi Dad: Ame\n',
 'ysrfoundation2: Arey EDI accident naku estam raa ee movie lo\n',
 'ysrfoundation2: https://youtube.com/shorts/GM1tIe2jD-c?si=M_ehiKgESYV0vU7F\n',
 'ysrfoundation2: <Media omitted>\n',
 'ysrfoundation2: Naa kallu Edo chepuko\n']

In [152]:
df

                                          user_message            message_date
0    Messages and calls are end-to-end encrypted. N...  30/11/2023, 7:44 am -
1                                ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
2                                   Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
3                               ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
4                            ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -
..                                                 ...                     ...
455                                 Sahithi Dad: Ame\n  07/01/2024, 8:42 pm -
456  ysrfoundation2: Arey EDI accident naku estam r...  07/01/2024, 9:07 pm -
457  ysrfoundation2: https://youtube.com/shorts/GM1...  10/01/2024, 6:14 pm -
458                  ysrfoundation2: <Media omitted>\n  10/01/2024, 6:54 pm -
459            ysrfoundation2: Naa kallu Edo chepuko\n  10/01/2024, 6:55 pm -

[460 rows x 2 columns]

In [153]:
    users = []
    messages = []

In [154]:
for message in df['user_message']:
        entry = re.split('([\w\W]+?):\s', message)
        if entry[1: ]:
            users.append(entry[1])
            messages.append(entry[2])

In [155]:
users

['ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'ysrfoundation2',
 'Sahithi Dad',
 'Sahithi Dad',
 'Sahithi Dad',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2',
 'ysrfoundation2']

In [156]:

messages

['Hii\n',
 'Hlo\n',
 'Hiii\n',
 'Sahithi\n',
 'What are you doing\n',
 'Ntg\n',
 'Ra\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'null\n',
 'null\n',
 'null\n',
 'Am ayna telisinda\n',
 'Ledhu sir chuda lee anta\n',
 'Avunaa\n',
 'Hmm\n',
 'Burra paadu\n',
 'Asalu\n',
 'Sahithi pottidi ki msg cheyu raa\n',
 'Haa\n',
 'Yevariki\n',
 'Chellu kaa\n',
 'Mi head ki\n',
 'Haa\n',
 'Na gubalu yegara gottey galadu le\n',
 '🤣🤣🤣\n',
 'Sare tinnava\n',
 'Haa\n',
 'Nuvvo\n',
 'Call cheyyamane vadiki\n',
 'Vadhu\n',
 'Le\n',
 'Ledhu time chusava\n',
 'Hoo\n',
 'Ade chepthunna\n',
 'Hmm\n',
 'Ohh\n',
 'Ledu ledu\n',
 'Hoo\n',
 'Inkante\n',
 'Burra paadu\n',
 'Kadupula noppi\n',
 'Yeh visyam clarity ga telidhu\n',
 'Chi\n',
 'Am clg yeh babu\n',
 'Manadu\n',
 'Manadi\n',
 'Haa same feeling kani chepa lenu\n',
 '😢\n',
 'Sare Lee vadu reply Este niku msg chesta lee\n',
 'Kk\n',
 'Padmavathi clg kuda selavu\n',
 'Hoo appude adige sava\n',
 'Fast nenu\n',
 '<Media omitted>\n',
 'Selavu manaki kuda\n',
 'Tomorrow (05.12.23) college holiday\n',
 'S\n',
 'Super\n',
 'Am antha badha\n',
 'Arey maa Chelli pettamandi petta\n',
 'Niku badha ante CLG tmrw holiday estaro ledho ani\n',
 'Nakaa\n',
 'Ledhu naku ani pettali kani mistake\n',
 'Ohh\n',
 'Me chelli ki echara\n',
 'Selavu\n',
 'Haa\n',
 'Hi\n',
 'Chadivesava\n',
 'Ledhu\n',
 'Tmrw holiday estaro amo ani balance uncha\n',
 'Evvaru mari\n',
 'Hoo sare evvaku pothe ledhu\n',
 'Ante\n',
 'Jyothi akka vallu bojanam ki pilichara meku\n',
 'Epudu\n',
 'Repu\n',
 'Emo naku telidhu\n',
 'Me mummy ki adigi cheppu\n',
 'Sare kani\n',
 'Nuvvu chadesava\n',
 'Ledu ra\n',
 'Bayam vesthundi\n',
 'Naku\n',
 'Hoo\n',
 'Haaa\n',
 'Send me\n',
 '<Media omitted>\n',
 'Today\n',
 'Holiday\n',
 'Msg chudu grouplo\n',
 'Hoo super raa\n',
 'Orey\n',
 'Bojanalaki vasthava\n',
 'Shake\n',
 'Hiii\n',
 'Tinnava\n',
 'Hi\n',
 'Hiii\n',
 'Hlo\n',
 'Aishu\n',
 '💯\n',
 '😍😍\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Nice\n',
 '😚😚\n',
 '<Media omitted>\n',
 'Shop now on Meesho! \nhttps://www.meesho.com/s/p/4w7qta?utm_source=s_w\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'https://youtu.be/nZqD1FyXdBE?si=LgG8tjA9U4orjAjz\n',
 'Arey EDI oka sari chudu\n',
 'Ila vuntundi aa\n',
 'Haa\n',
 'Epudu Mari pondi\n',
 'Enti\n',
 'Pondi enti ra\n',
 'Epudu Mari poindhi  raa\n',
 'Baledu antunnava\n',
 'Ma intlo chala long antunnaru\n',
 'Ledhu raa super ga chesaru antunna\n',
 'Hoo\n',
 'Avunu\n',
 'Emo time undi kadha chudam\n',
 'Haa sare le\n',
 'Hmm\n',
 'Arey balloons ne phone lo order cheyu raa\n',
 'Epudu cheste aapudo vastadi\n',
 'Na phone lo nenu yeppudu pettaledu ra\n',
 'Ne phone lo petti money kavalante echestha\n',
 'Aishu ma nanna money adigaru ra\n',
 'Arey 350 ani chepamannadi taruvata chudam annadu\n',
 'Ok na\n',
 'Yevaru\n',
 'Ma mom\n',
 'Adi kaadu yeh babu\n',
 'Mari enti\n',
 'Cheppuluvi, kit vi\n',
 'Enti ardham kaledhu\n',
 'Phone cheyyala\n',
 'Cheppulu\n',
 'Baby kit usha valla babu ki teesukunnam kada\n',
 'Aa money\n',
 'Haa sare\n',
 'Nenu raanu ra\n',
 'Em\n',
 'Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru\n',
 'Hoo\n',
 'Haaa\n',
 'Sare kani money anta\n',
 '280 ra\n',
 'Monna 50 icha annav kada\n',
 '230\n',
 'Haa kk\n',
 'Haa sare\n',
 '🙏🏻\n',
 'Y\n',
 'Song baledha\n',
 'Super\n',
 'Anduke petta reasons em ledhu\n',
 'Aishu pettava photo\n',
 '<Media omitted>\n',
 'Enti ra\n',
 'Hii sahithi\n',
 'Hi ra\n',
 'Photo pettava\n',
 'Haa pedata lee\n',
 'Sry raledu endhuku ante dress change cheyledu\n',
 'Andhuke\n',
 'Paravaledu lee\n',
 'Akhila kavi vacharu\n',
 'Marchipoku e roju pettu\n',
 'Avunaa\n',
 'Haa\n',
 'Videos pettu\n',
 'Naku\n',
 'Puja vi\n',
 'Haa\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Aishu pettava\n',
 'Photo\n',
 'Haa\n',
 'Am annaru\n',
 'Oley hd vi pettamani cheppa kadey\n',
 '🫢\n',
 'Hi\n',
 'Hii\n',
 'Chadivesava madam\n',
 'Ledhu raa maths main chudali\n',
 'Chusava mari\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'You deleted this message\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Chadivesava\n',
 'Ledhu\n',
 'Nv brilliant le appudu kappudu ayna chusi rasesthav\n',
 'Haa avunu lee\n',
 'Yes its true\n',
 'Aishu e question chadivava\n',
 'Nanu asalu em chadavale\n',
 'Avunaa\n',
 'Sare le\n',
 'Hmm\n',
 'Send me\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Aishu\n',
 'Adigava\n',
 'Vallaki  am annaru\n',
 'Avariki\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Anu monika mani vallaki\n',
 'Haa kk moni , rama\n',
 'Anu kudha m avvaka pote  annadi\n',
 'Hii\n',
 'Hii\n',
 'Hi\n',
 'Hiii\n',
 'Am doing\n',
 'Hiii\n',
 'Hi\n',
 'Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa\n',
 'Rama raadhu aa\n',
 'Ante mrng varuku telidhu\n',
 'Am alaga\n',
 'Emo\n',
 'Avuna\n',
 'Hmm\n',
 'Inko 4members yevaru ra\n',
 'Chinnamudu , paiga vallu avaro anta family nee\n',
 'Ohh kk le\n',
 'Hmm\n',
 'Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali\n',
 'Sare\n',
 'Sare inka\n',
 'Cheppali\n',
 'Ante tmrw kosam adaina cheppu\n',
 'Games aa\n',
 'Haa\n',
 'Okka 5min aaagu\n',
 'Msg chesthanu\n',
 'Kk\n',
 'Yeh dress vesthav\n',
 'Nenu birthday di anukuntunna u\n',
 'Avunaa\n',
 'Hmm\n',
 'Mari nenu am veyyali\n',
 'Authe\n',
 'Emo nuvve Alo chinchu\n',
 'Cheppu nuvvu\n',
 'Naku ala telustunndi\n',
 'Na dresslu anni chusav kada\n',
 'Emo raa nuvve decide avvu\n',
 'Sare le\n',
 '<Media omitted>\n',
 'Edi ok naa\n',
 'Haa kk\n',
 'Kk le\n',
 'Hmm\n',
 'Leka pothe inko top vundi\n',
 'Ado\n',
 'Kothadi adi ayna vadesthanu le\n',
 'Haa ne estam nee dress\n',
 'Sare le\n',
 'Hmm\n',
 'Inkem games adugu mani vallaki\n',
 'Hiii sahi\n',
 'Anu ki phone cheyu oka sari adugu\n',
 'Sare\n',
 'Hi\n',
 'Enni gantalaki ra\n',
 'Aishu phone pay number pettu money phone pay chestha\n',
 'null\n',
 '9949437849\n',
 'Kk naa\n',
 'Kk\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Orey phone pay maadi avvatledu limit aypoyindi madi e roju di\n',
 'Mrng thechi echesthanu me daddy ki cheppu\n',
 'Kk\n',
 'Evena pics mari levaa\n',
 'Haa rassu ki cheppa\n',
 'Tana daggara konni vunnay\n',
 'Oka sari nuvvu msg pettu\n',
 'Kk\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Hi\n',
 'Hiii\n',
 'https://www.instagram.com/reel/C1J_HW6pjTb/?igsh=N2ZiNzVhMjY2OA==\n',
 '🤣🤣\n',
 '😂\n',
 'Date chusava\n',
 '<Media omitted>\n',
 'Sahithi nee English key nadaggara vundi\n',
 'Ade vethika\n',
 'Chala sepu\n',
 'Hoo nenu epudo msg petta\n',
 'Mobile vundadu ani telusu gaa neku\n',
 '12th answer pettava\n',
 'null\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Tqqq❤️😘🥰\n',
 'Abho chalu lee\n',
 '😄\n',
 'Open chesava\n',
 'Set\n',
 'Haa chusa\n',
 'Pump evvale ante\n',
 'Anni kk\n',
 'Evvaleda pump\n',
 'Ledhu\n',
 'Kkk\n',
 '<Media omitted>\n',
 'https://youtube.com/shorts/Ze8DjY_4kVQ?si=CXBIMqJh3p7cPOzm\n',
 'Aishu\n',
 'Aishu\n',
 'Photo pettu\n',
 'Aa photo\n',
 'Frame\n',
 'Pack chesadhu vadu\n',
 'Avuna\n',
 'Nv kuda chudaledha\n',
 'Hmm\n',
 'Ledhu\n',
 'Indhaka yekkadiki vellav\n',
 'Gift kosam aa\n',
 'Sorry wrong answer pakodi kosam\n',
 'Avunaa\n',
 'Hmm\n',
 'Gift konta annav\n',
 'Haa tmrw suprise miku ,anu ki kudha\n',
 'Nku cheppu le\n',
 'Parledu\n',
 'Tmrw chustav kadha\n',
 'Cheppu\n',
 'Ra\n',
 'Bye muggulu chustunna\n',
 'Cheppava\n',
 'Anthe n\n',
 'Nenu neku telisinatte chesa ga yedi chesinaa\n',
 'Edi cheating asalu\n',
 'Ledhu raa inka em konalo decide avvale anduke\n',
 'Avunaa\n',
 'Hmm\n',
 'Aishu\n',
 'Aishu chude yelaga chesado\n',
 'Chala kopam ga vundi vaadi medha\n',
 'Haa delete kudha cheya lee\n',
 'Cheyyadu vaadu nku telusu\n',
 'Haa Mari em chestam nenu , nuvvu kudha chudale\n',
 'Hmm\n',
 'Arey cake kosam money enta\n',
 'Cheppa lee\n',
 'Sare anu status chusava\n',
 'Me estham yeh\n',
 'Vaadu inka delete cheyleda\n',
 'Naku chala chiraku ga vundi\n',
 'Anu kuda status pettisindi\n',
 '<Media omitted>\n',
 'Vinu\n',
 'Aishu\n',
 'null\n',
 'Tmrw chemistry bullet evvu\n',
 'null\n',
 '<Media omitted>\n',
 'https://www.instagram.com/reel/C1i2zXhp-En/?igsh=MWp4bDQ1MmhxemtyOQ==\n',
 '<Media omitted>\n',
 'Arey msg cheyu tanuja ki\n',
 'Plss\n',
 'Kk\n',
 '<Media omitted>\n',
 'Arey manam Ela nee epudaina photos tesukundam kk naa\n',
 'Done done 👍👍👍\n',
 'Sare chemistry photos pettu\n',
 '<Media omitted>\n',
 '<Media omitted>\n',
 'Ammo chadivedham ane\n',
 'Haa kani epudu di ee paper\n',
 'Repatiki\n',
 '<Media omitted>\n',
 'Hiiii\n',
 'Hi\n',
 'Ame\n',
 'Arey EDI accident naku estam raa ee movie lo\n',
 'https://youtube.com/shorts/GM1tIe2jD-c?si=M_ehiKgESYV0vU7F\n',
 '<Media omitted>\n',
 'Naa kallu Edo chepuko\n']

In [157]:
len(users)

459

In [158]:
len(messages)

459

In [159]:
len(df)

460

In [160]:
df

                                          user_message            message_date
0    Messages and calls are end-to-end encrypted. N...  30/11/2023, 7:44 am -
1                                ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
2                                   Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
3                               ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
4                            ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -
..                                                 ...                     ...
455                                 Sahithi Dad: Ame\n  07/01/2024, 8:42 pm -
456  ysrfoundation2: Arey EDI accident naku estam r...  07/01/2024, 9:07 pm -
457  ysrfoundation2: https://youtube.com/shorts/GM1...  10/01/2024, 6:14 pm -
458                  ysrfoundation2: <Media omitted>\n  10/01/2024, 6:54 pm -
459            ysrfoundation2: Naa kallu Edo chepuko\n  10/01/2024, 6:55 pm -

[460 rows x 2 columns]

In [161]:
df = df.drop(0)

In [162]:
df = df.reset_index(drop=True)

In [163]:
df.head()

                           user_message            message_date
0                 ysrfoundation2: Hii\n  30/11/2023, 7:45 am -
1                    Sahithi Dad: Hlo\n  30/11/2023, 7:49 am -
2                ysrfoundation2: Hiii\n  03/12/2023, 1:34 pm -
3             ysrfoundation2: Sahithi\n  03/12/2023, 1:52 pm -
4  ysrfoundation2: What are you doing\n  03/12/2023, 1:52 pm -

In [164]:
len(users)

459

In [165]:
df['users'] = users 
df['messages'] = messages

In [75]:
df.head()

,user_message,message_date,users,messages
0,ysrfoundation2: Hii\n,"30/11/2023, 7:45 am -",ysrfoundation2,Hii\n
1,Sahithi Dad: Hlo\n,"30/11/2023, 7:49 am -",Sahithi Dad,Hlo\n
2,ysrfoundation2: Hiii\n,"03/12/2023, 1:34 pm -",ysrfoundation2,Hiii\n
3,ysrfoundation2: Sahithi\n,"03/12/2023, 1:52 pm -",ysrfoundation2,Sahithi\n
4,ysrfoundation2: What are you doing\n,"03/12/2023, 1:52 pm -",ysrfoundation2,What are you doing\n

In [76]:
df  = df.drop('user_message',axis=1)

In [77]:
df.head()

             message_date           users              messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii\n
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo\n
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii\n
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi\n
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing\n

In [82]:
df1 = df.copy()

In [166]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [167]:
df1 = df1[df1['messages']!='<Media omitted>\n']

In [168]:
df1 = df1[df1['messages']!='null\n']

In [169]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [170]:
len(df1)

352

In [180]:
for i in range(len(df1)):
    if('<This Message Was Edited>' in df1.loc[i]['messages']):
        df1.loc[i]['messages'] = df1.loc[i]['messages'].replace('<This Message Was Edited>','')
    if('\n' in df1.loc[i]['messages']):
        df1.loc[i]['messages'] = df1.loc[i]['messages'].replace('\n','')
    if('http' in df1.loc[i]['messages']):
        df1.drop(i,inplace=True)

In [181]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [182]:
df1 = df1.reset_index(drop=True)

In [183]:
df1

,message_date,users,messages
0,"30/11/2023, 7:45 am -",ysrfoundation2,Hii
1,"30/11/2023, 7:49 am -",Sahithi Dad,Hlo
2,"03/12/2023, 1:34 pm -",ysrfoundation2,Hiii
3,"03/12/2023, 1:52 pm -",ysrfoundation2,Sahithi
4,"03/12/2023, 1:52 pm -",ysrfoundation2,What are you doing
...,...,...,...
341,"06/01/2024, 8:58 pm -",Sahithi Dad,Hiiii
342,"07/01/2024, 8:40 pm -",Sahithi Dad,Hi
343,"07/01/2024, 8:42 pm -",Sahithi Dad,Ame
344,"07/01/2024, 9:07 pm -",ysrfoundation2,Arey EDI accident naku estam raa ee movie lo
345,"10/01/2024, 6:55 pm -",ysrfoundation2,Naa kallu Edo chepuko

In [184]:
df1.loc[0]['messages']

'Hii'

In [185]:
for i in range(len(df1)):
    df1.loc[i]['messages']  = df1.loc[i]['messages'].replace('\n', '')

In [186]:
df1

,message_date,users,messages
0,"30/11/2023, 7:45 am -",ysrfoundation2,Hii
1,"30/11/2023, 7:49 am -",Sahithi Dad,Hlo
2,"03/12/2023, 1:34 pm -",ysrfoundation2,Hiii
3,"03/12/2023, 1:52 pm -",ysrfoundation2,Sahithi
4,"03/12/2023, 1:52 pm -",ysrfoundation2,What are you doing
...,...,...,...
341,"06/01/2024, 8:58 pm -",Sahithi Dad,Hiiii
342,"07/01/2024, 8:40 pm -",Sahithi Dad,Hi
343,"07/01/2024, 8:42 pm -",Sahithi Dad,Ame
344,"07/01/2024, 9:07 pm -",ysrfoundation2,Arey EDI accident naku estam raa ee movie lo
345,"10/01/2024, 6:55 pm -",ysrfoundation2,Naa kallu Edo chepuko

In [187]:
df2 = df1.copy()

In [188]:
person1 = df2.users.unique()[0]
person2 = df2.users.unique()[1]

In [189]:
person1

'ysrfoundation2'

In [190]:
person2

'Sahithi Dad'

In [191]:
for i in range(len(df2)):
    if df2.loc[i]['users'] == person1:
        df2.loc[i]['users'] = 'A'
    elif df2.loc[i]['users'] == person2:
        df2.loc[i]['users'] = 'B'

In [196]:
for i in range(len(df1)):
    if df1.loc[i]['users'] == person1:
        df1.loc[i]['users'] = 'A'
    elif df1.loc[i]['users'] == person2:
        df1.loc[i]['users'] = 'B'

In [192]:
df2.head()

             message_date users            messages
0  30/11/2023, 7:45 am -      A                 Hii
1  30/11/2023, 7:49 am -      B                 Hlo
2  03/12/2023, 1:34 pm -      A                Hiii
3  03/12/2023, 1:52 pm -      A             Sahithi
4  03/12/2023, 1:52 pm -      A  What are you doing

In [193]:
df1.head()

             message_date           users            messages
0  30/11/2023, 7:45 am -   ysrfoundation2                 Hii
1  30/11/2023, 7:49 am -      Sahithi Dad                 Hlo
2  03/12/2023, 1:34 pm -   ysrfoundation2                Hiii
3  03/12/2023, 1:52 pm -   ysrfoundation2             Sahithi
4  03/12/2023, 1:52 pm -   ysrfoundation2  What are you doing

In [43]:
df2.to_csv('pra_1.csv')

In [44]:
df2.head()

         message_date users                        messages
0  12/27/23, 21:36 -      A                              Ok
1  12/27/23, 21:36 -      B                  Nedhi aipoyaka
2  12/27/23, 21:36 -      B  Naku cheppu maths..4th chapter
3  12/27/23, 21:37 -      B  Okay na...Marchipoku raa nanaa
4  12/28/23, 00:03 -      B                           Hello

In [48]:
model = AutoModelForSeq2SeqLM.from_pretrained("facebook/nllb-200-distilled-600M")
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")

In [61]:
save_directory = "/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/artifacts"
model.save_pretrained(save_directory)
tokenizer.save_pretrained(save_directory)

NameError: name 'model' is not defined

In [19]:
xlit_engine = Nonex
def initialize_xlit_engine(language_code="te", beam_width=10):
    global xlit_engine
    if xlit_engine is None:
        xlit_engine = XlitEngine(language_code, beam_width=beam_width)

In [55]:
def transliterator(df):
    global xlit_engine
    initialize_xlit_engine()
    outputs = []
    for i in range(len(df)): 
        output = xlit_engine.translit_sentence(df.loc[i]['messages'])
        outputs.append(output['te'])
    df['translit_msgs'] = outputs
    return df

In [2]:
df3 = pd.read_csv('pra_1.csv',index_col=None)

In [3]:
df3.head()

   Unnamed: 0        message_date users                        messages
0           0  12/27/23, 21:36 -      A                              Ok
1           1  12/27/23, 21:36 -      B                  Nedhi aipoyaka
2           2  12/27/23, 21:36 -      B  Naku cheppu maths..4th chapter
3           3  12/27/23, 21:37 -      B  Okay na...Marchipoku raa nanaa
4           4  12/28/23, 00:03 -      B                           Hello

In [4]:
df3.drop('Unnamed: 0',axis=1,inplace=True)

In [56]:
df4 = df3.copy()

In [57]:
df4 = transliterator(df4)

In [58]:
df4

,message_date,users,messages,tranlit_msg
0,"12/27/23, 21:36 -",A,Ok,ఒక్
1,"12/27/23, 21:36 -",B,Nedhi aipoyaka,నేది అయిపోయాక
2,"12/27/23, 21:36 -",B,Naku cheppu maths..4th chapter,నాకు చెప్పు మాత్స్..౪త్ చాప్టర్
3,"12/27/23, 21:37 -",B,Okay na...Marchipoku raa nanaa,ఒకే నా...మర్చిపోకు రా ననా
4,"12/28/23, 00:03 -",B,Hello,హెల్లో
...,...,...,...,...
255,"12/28/23, 21:16 -",A,En,ఎన్
256,"12/28/23, 21:16 -",A,Em vacation,ఇఎం వెకేషన్
257,"12/28/23, 21:16 -",A,Mari,మరి
258,"12/28/23, 21:16 -",A,Naa kosamu ani sollu,నా కోసము అని సొల్లు
259,"12/28/23, 21:16 -",A,Chepavu,చేపవు

In [59]:
df4.to_csv('pra_2.csv')

In [ ]:
save_directory = "/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/artifacts"

In [ ]:
loaded_model = AutoModelForSeq2SeqLM.from_pretrained(save_directory)
loaded_tokenizer = AutoTokenizer.from_pretrained(save_directory)

In [8]:
def translator(df):
    save_directory = "/home/user/Documents/ML_DL_PROJECTS/WhatsAppChatAnalysisProject/artifacts"
    loaded_model = AutoModelForSeq2SeqLM.from_pretrained(save_directory)
    loaded_tokenizer = AutoTokenizer.from_pretrained(save_directory)    
    obj = pipeline('translation', model=loaded_model, tokenizer=loaded_tokenizer, src_lang="tel_Telu", tgt_lang='eng_Latn', max_length = 10000)
    outputs = []
    for i in range(len(df)):
        output = obj(df.loc[i]['translit_msgs'])
        outputs.append(output[0]['translation_text'])
    df['translate_msgs'] = outputs
    return df

In [66]:
df5 = df4.copy()

In [9]:
df5 = pd.read_csv('pra_2.csv')

In [12]:
df5 = df5.drop('Unnamed: 0',axis=1)

In [13]:
df5 = translator(df5)

In [27]:
df5.to_csv('pra_3.csv')

In [28]:
df5.head()

,message_date,users,messages,translit_msgs,translate_msgs
0,"12/27/23, 21:36 -",A,Ok,ఒక్,"Oh, my God."
1,"12/27/23, 21:36 -",B,Nedhi aipoyaka,నేది అయిపోయాక,When I was done
2,"12/27/23, 21:36 -",B,Naku cheppu maths..4th chapter,నాకు చెప్పు మాత్స్..౪త్ చాప్టర్,"Tell me, Maths, the fourth chapter."
3,"12/27/23, 21:37 -",B,Okay na...Marchipoku raa nanaa,ఒకే నా...మర్చిపోకు రా ననా,"Just remember, my dear."
4,"12/28/23, 00:03 -",B,Hello,హెల్లో,"Hello, my name is"

In [30]:
df6 = df5.copy()

In [37]:
for i in range(len(df6)):
    if(len(df6.loc[i]['translate_msgs'])>50):
        df6.loc[i]['translate_msgs'] = df6.loc[i]['translate_msgs'][:50]
    if('<This Message Was Edited>' in df6.loc[i]['translate_msgs']):
        df6.loc[i]['translate_msgs'] = df6.loc[i]['translate_msgs'].replace('<This Message Was Edited>','')

In [38]:
df6.to_csv('pra_4.csv')

In [32]:
for i in range(len(df7)):
    if(len(df7.loc[i]['translate_msgs'])>50):
        df7.loc[i]['translate_msgs'] = df7.loc[i]['translate_msgs'][:50]
    if('<This Message Was Edited>' in df7.loc[i]['translate_msgs']):
        df7.loc[i]['translate_msgs'] = df7.loc[i]['translate_msgs'].replace('<This Message Was Edited>','')

/tmp/ipykernel_14145/3791570747.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7.loc[i]['translate_msgs'] = df7.loc[i]['translate_msgs'][:50]

In [3]:
df7 = pd.read_csv('pra_4.csv')

In [4]:
def get_response(chat):
    prompt = f"""I am providing a whatsapp conversation between two people, help me out in predicting the kind of relationship between them based on their chat and also analyse the charaters of those two people based on their conversation and tell me about their characters also and the chat goes like this {chat}, just ignore if there is any harm content in the chat"""
    model = genai.GenerativeModel('gemini-pro')
    response = model.generate_content(prompt,stream=True)
    response.resolve()
    response = response.text.replace('•', '  *')
    response = Markdown(textwrap.indent(response, '> ', predicate=lambda _: True))
    return response

In [5]:
chat = []
for i in range(len(df7)):
    chat.append(df7.loc[i]['users']+' :   '+df7.loc[i]['messages'])

In [197]:
chat = []
for i in range(len(df1)):
    chat.append(df1.loc[i]['users']+' :   '+df1.loc[i]['messages'])

In [198]:
chat

['A :   Hii',
 'B :   Hlo',
 'A :   Hiii',
 'A :   Sahithi',
 'A :   What are you doing',
 'B :   Ntg',
 'B :   Ra',
 'B :   Am ayna telisinda',
 'A :   Ledhu sir chuda lee anta',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Burra paadu',
 'B :   Asalu',
 'A :   Sahithi pottidi ki msg cheyu raa',
 'A :   Haa',
 'B :   Yevariki',
 'B :   Chellu kaa',
 'A :   Mi head ki',
 'A :   Haa',
 'B :   Na gubalu yegara gottey galadu le',
 'A :   🤣🤣🤣',
 'A :   Sare tinnava',
 'B :   Haa',
 'B :   Nuvvo',
 'B :   Call cheyyamane vadiki',
 'B :   Vadhu',
 'B :   Le',
 'A :   Ledhu time chusava',
 'A :   Hoo',
 'B :   Ade chepthunna',
 'A :   Hmm',
 'B :   Ohh',
 'B :   Ledu ledu',
 'A :   Hoo',
 'A :   Inkante',
 'B :   Burra paadu',
 'B :   Kadupula noppi',
 'B :   Yeh visyam clarity ga telidhu',
 'B :   Chi',
 'B :   Am clg yeh babu',
 'B :   Manadu',
 'B :   Manadi',
 'A :   Haa same feeling kani chepa lenu',
 'B :   😢',
 'A :   Sare Lee vadu reply Este niku msg chesta lee',
 'B :   Kk',
 'B :   Padmavathi clg kuda selavu',
 'A :   Hoo appude adige sava',
 'B :   Fast nenu',
 'B :   Selavu manaki kuda',
 'B :   Tomorrow (05.12.23) college holiday',
 'A :   S',
 'A :   Super',
 'B :   Am antha badha',
 'A :   Arey maa Chelli pettamandi petta',
 'A :   Niku badha ante CLG tmrw holiday estaro ledho ani',
 'B :   Nakaa',
 'A :   Ledhu naku ani pettali kani mistake',
 'B :   Ohh',
 'B :   Me chelli ki echara',
 'B :   Selavu',
 'A :   Haa',
 'B :   Hi',
 'B :   Chadivesava',
 'A :   Ledhu',
 'A :   Tmrw holiday estaro amo ani balance uncha',
 'B :   Evvaru mari',
 'A :   Hoo sare evvaku pothe ledhu',
 'A :   Ante',
 'B :   Jyothi akka vallu bojanam ki pilichara meku',
 'A :   Epudu',
 'B :   Repu',
 'A :   Emo naku telidhu',
 'B :   Me mummy ki adigi cheppu',
 'A :   Sare kani',
 'A :   Nuvvu chadesava',
 'B :   Ledu ra',
 'B :   Bayam vesthundi',
 'B :   Naku',
 'A :   Hoo',
 'B :   Haaa',
 'B :   Send me',
 'B :   Today',
 'B :   Holiday',
 'B :   Msg chudu grouplo',
 'A :   Hoo super raa',
 'B :   Orey',
 'B :   Bojanalaki vasthava',
 'B :   Shake',
 'A :   Hiii',
 'A :   Tinnava',
 'B :   Hi',
 'A :   Hiii',
 'B :   Hlo',
 'B :   Aishu',
 'B :   💯',
 'A :   😍😍',
 'B :   Nice',
 'A :   😚😚',
 'A :   Arey EDI oka sari chudu',
 'B :   Ila vuntundi aa',
 'A :   Haa',
 'A :   Epudu Mari pondi',
 'B :   Enti',
 'B :   Pondi enti ra',
 'A :   Epudu Mari poindhi  raa',
 'B :   Baledu antunnava',
 'B :   Ma intlo chala long antunnaru',
 'A :   Ledhu raa super ga chesaru antunna',
 'A :   Hoo',
 'B :   Avunu',
 'A :   Emo time undi kadha chudam',
 'B :   Haa sare le',
 'A :   Hmm',
 'A :   Arey balloons ne phone lo order cheyu raa',
 'A :   Epudu cheste aapudo vastadi',
 'B :   Na phone lo nenu yeppudu pettaledu ra',
 'B :   Ne phone lo petti money kavalante echestha',
 'B :   Aishu ma nanna money adigaru ra',
 'A :   Arey 350 ani chepamannadi taruvata chudam annadu',
 'A :   Ok na',
 'B :   Yevaru',
 'A :   Ma mom',
 'B :   Adi kaadu yeh babu',
 'A :   Mari enti',
 'B :   Cheppuluvi, kit vi',
 'A :   Enti ardham kaledhu',
 'A :   Phone cheyyala',
 'B :   Cheppulu',
 'B :   Baby kit usha valla babu ki teesukunnam kada',
 'B :   Aa money',
 'A :   Haa sare',
 'B :   Nenu raanu ra',
 'A :   Em',
 'B :   Ma nanna abbailu gatta vuntaru mancholu kaadu antunnaru',
 'A :   Hoo',
 'B :   Haaa',
 'A :   Sare kani money anta',
 'B :   280 ra',
 'B :   Monna 50 icha annav kada',
 'B :   230',
 'A :   Haa kk',
 'B :   Haa sare',
 'B :   🙏🏻',
 'B :   Y',
 'A :   Song baledha',
 'B :   Super',
 'A :   Anduke petta reasons em ledhu',
 'B :   Aishu pettava photo',
 'B :   Enti ra',
 'A :   Hii sahithi',
 'B :   Hi ra',
 'B :   Photo pettava',
 'A :   Haa pedata lee',
 'B :   Sry raledu endhuku ante dress change cheyledu',
 'B :   Andhuke',
 'A :   Paravaledu lee',
 'A :   Akhila kavi vacharu',
 'B :   Marchipoku e roju pettu',
 'B :   Avunaa',
 'A :   Haa',
 'B :   Videos pettu',
 'B :   Naku',
 'B :   Puja vi',
 'A :   Haa',
 'B :   Aishu pettava',
 'B :   Photo',
 'A :   Haa',
 'B :   Am annaru',
 'B :   Oley hd vi pettamani cheppa kadey',
 'B :   🫢',
 'B :   Hi',
 'A :   Hii',
 'B :   Chadivesava madam',
 'A :   Ledhu raa maths main chudali',
 'B :   Chusava mari',
 'A :   You deleted this message',
 'B :   Chadivesava',
 'A :   Ledhu',
 'B :   Nv brilliant le appudu kappudu ayna chusi rasesthav',
 'A :   Haa avunu lee',
 'B :   Yes its true',
 'B :   Aishu e question chadivava',
 'A :   Nanu asalu em chadavale',
 'B :   Avunaa',
 'B :   Sare le',
 'A :   Hmm',
 'B :   Send me',
 'B :   Aishu',
 'B :   Adigava',
 'B :   Vallaki  am annaru',
 'A :   Avariki',
 'B :   Anu monika mani vallaki',
 'A :   Haa kk moni , rama',
 'A :   Anu kudha m avvaka pote  annadi',
 'A :   Hii',
 'B :   Hii',
 'B :   Hi',
 'A :   Hiii',
 'B :   Am doing',
 'A :   Hiii',
 'B :   Hi',
 'A :   Arey rama , hema ,anu, vedha ki vadhi leste vachey vallaku count cheste 20 ayyaru raa',
 'B :   Rama raadhu aa',
 'A :   Ante mrng varuku telidhu',
 'B :   Am alaga',
 'A :   Emo',
 'B :   Avuna',
 'A :   Hmm',
 'B :   Inko 4members yevaru ra',
 'A :   Chinnamudu , paiga vallu avaro anta family nee',
 'B :   Ohh kk le',
 'A :   Hmm',
 'A :   Sare Lee raa housi book tecchamu tmrw game vadham inka amito mire cheppali',
 'B :   Sare',
 'A :   Sare inka',
 'B :   Cheppali',
 'A :   Ante tmrw kosam adaina cheppu',
 'B :   Games aa',
 'A :   Haa',
 'B :   Okka 5min aaagu',
 'B :   Msg chesthanu',
 'A :   Kk',
 'B :   Yeh dress vesthav',
 'A :   Nenu birthday di anukuntunna u',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Mari nenu am veyyali',
 'B :   Authe',
 'A :   Emo nuvve Alo chinchu',
 'B :   Cheppu nuvvu',
 'A :   Naku ala telustunndi',
 'B :   Na dresslu anni chusav kada',
 'A :   Emo raa nuvve decide avvu',
 'B :   Sare le',
 'B :   Edi ok naa',
 'A :   Haa kk',
 'B :   Kk le',
 'A :   Hmm',
 'B :   Leka pothe inko top vundi',
 'A :   Ado',
 'B :   Kothadi adi ayna vadesthanu le',
 'A :   Haa ne estam nee dress',
 'B :   Sare le',
 'A :   Hmm',
 'B :   Inkem games adugu mani vallaki',
 'A :   Hiii sahi',
 'A :   Anu ki phone cheyu oka sari adugu',
 'B :   Sare',
 'B :   Hi',
 'B :   Enni gantalaki ra',
 'B :   Aishu phone pay number pettu money phone pay chestha',
 'A :   9949437849',
 'A :   Kk naa',
 'B :   Kk',
 'B :   Orey phone pay maadi avvatledu limit aypoyindi madi e roju di',
 'B :   Mrng thechi echesthanu me daddy ki cheppu',
 'A :   Kk',
 'B :   Evena pics mari levaa',
 'A :   Haa rassu ki cheppa',
 'A :   Tana daggara konni vunnay',
 'A :   Oka sari nuvvu msg pettu',
 'B :   Kk',
 'B :   Hi',
 'A :   Hiii',
 'A :   🤣🤣',
 'B :   😂',
 'B :   Date chusava',
 'A :   Sahithi nee English key nadaggara vundi',
 'B :   Ade vethika',
 'B :   Chala sepu',
 'A :   Hoo nenu epudo msg petta',
 'B :   Mobile vundadu ani telusu gaa neku',
 'B :   12th answer pettava',
 'B :   Tqqq❤️😘🥰',
 'A :   Abho chalu lee',
 'B :   😄',
 'B :   Open chesava',
 'B :   Set',
 'A :   Haa chusa',
 'A :   Pump evvale ante',
 'A :   Anni kk',
 'B :   Evvaleda pump',
 'A :   Ledhu',
 'B :   Kkk',
 'B :   Aishu',
 'B :   Aishu',
 'B :   Photo pettu',
 'A :   Aa photo',
 'B :   Frame',
 'A :   Pack chesadhu vadu',
 'B :   Avuna',
 'B :   Nv kuda chudaledha',
 'A :   Hmm',
 'A :   Ledhu',
 'B :   Indhaka yekkadiki vellav',
 'B :   Gift kosam aa',
 'A :   Sorry wrong answer pakodi kosam',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Gift konta annav',
 'A :   Haa tmrw suprise miku ,anu ki kudha',
 'B :   Nku cheppu le',
 'B :   Parledu',
 'A :   Tmrw chustav kadha',
 'B :   Cheppu',
 'B :   Ra',
 'A :   Bye muggulu chustunna',
 'B :   Cheppava',
 'B :   Anthe n',
 'B :   Nenu neku telisinatte chesa ga yedi chesinaa',
 'B :   Edi cheating asalu',
 'A :   Ledhu raa inka em konalo decide avvale anduke',
 'B :   Avunaa',
 'A :   Hmm',
 'B :   Aishu',
 'B :   Aishu chude yelaga chesado',
 'B :   Chala kopam ga vundi vaadi medha',
 'A :   Haa delete kudha cheya lee',
 'B :   Cheyyadu vaadu nku telusu',
 'A :   Haa Mari em chestam nenu , nuvvu kudha chudale',
 'A :   Hmm',
 'A :   Arey cake kosam money enta',
 'A :   Cheppa lee',
 'A :   Sare anu status chusava',
 'B :   Me estham yeh',
 'B :   Vaadu inka delete cheyleda',
 'B :   Naku chala chiraku ga vundi',
 'B :   Anu kuda status pettisindi',
 'B :   Vinu',
 'B :   Aishu',
 'A :   Tmrw chemistry bullet evvu',
 'A :   Arey msg cheyu tanuja ki',
 'A :   Plss',
 'B :   Kk',
 'A :   Arey manam Ela nee epudaina photos tesukundam kk naa',
 'B :   Done done 👍👍👍',
 'A :   Sare chemistry photos pettu',
 'B :   Ammo chadivedham ane',
 'A :   Haa kani epudu di ee paper',
 'B :   Repatiki',
 'B :   Hiiii',
 'B :   Hi',
 'B :   Ame',
 'A :   Arey EDI accident naku estam raa ee movie lo',
 'A :   Naa kallu Edo chepuko']

In [200]:
person1

'ysrfoundation2'

In [199]:
get_response(chat)

> **Relationship:**
>
> The relationship between A and B appears to be friendly and casual, possibly between friends or acquaintances. They communicate in a familiar manner, using nicknames and emojis, and discuss everyday topics such as activities, plans, and personal updates.
>
> **Character Analysis:**
>
> **A:**
>
> - Outgoing and friendly: A initiates conversations, uses playful language, and expresses enthusiasm.
> - Organized and detail-oriented: A often asks for specific information and follows up on requests.
> - Considerate and accommodating: A shows concern for B's feelings and tries to accommodate their preferences.
>
> **B:**
>
> - Relaxed and easy-going: B responds calmly to A's questions and requests, and does not seem to get stressed or agitated.
> - Open to suggestions and willing to help: B agrees to carry out tasks and requests made by A.
> - Playful and humorous: B uses emojis and jokes to add a lighthearted tone to the conversation.
>
> Overall, A and B seem to have a positive and comfortable relationship, characterized by mutual respect and a sense of camaraderie.

In [45]:
f = open('dataset/WhatsApp Chat with NAGA JYOTHIKA (MBIPC NZD).txt','r',encoding='utf-8')

In [46]:
chat1 = f.read()

In [47]:
chat2 = chat1.split('\n')

In [48]:
chat2

['A: Hello,Beee exam raayaledha?',
 'B: Ledhu',
 'B: Why?',
 'A: 9th chart photos vunnaya?',
 'B: Ledhu',
 'A: Sarle...',
 'B: Ha',
 'A: Poni chart vundha?',
 'A: Twaraga cheppu..',
 'B: Haa',
 'B: Undhi',
 'A: Ivvagalava 9th chart practice chesi istha...',
 'B: Sare',
 'B: Ekkada unnav',
 'A: Sare nenu counter dhaggara vunta theeskoni ra',
 'B: Haa',
 'B: Ok correct diagram unte pettu',
 'B: Chuskunta',
 'A: Kk',
 'A: Actually, nenu naa clz okadiki photos pettamanna, nee dhaggara chart theeskunna tharvaatha vaadu pettaadu, andhulondhe ee diagram',
 'B: Oh ok',
 'B: Hello',
 'B: Ipoyindha?',
 'A: Yeah',
 'A: 5 mins thintunna',
 'B: Oh ok',
 'A: Vachaaka istha',
 'B: Vachaka msg chey',
 'B: Ok',
 'B: 9th chart lo 3rd question pic unte pettava',
 'A: sorry for delay...',
 'B: Tq no problem',
 'B: 10 th dhi kuda pettava',
 'A: Ok👍',
 'B: K tq',
 'A: Hello, repu camp ki velthunnaara?',
 'B: Nope',
 'B: Hey..tnx',
 'A: Vellatle...',
 'A: Sem ana...',
 '1B: Yeah',
 'A: Entha madhi velthunnaaru?',
 'B: Velle vallu ithe 23 veltharu anta',
 'B: Max velthunnaru',
 'B: Oka 2 or 3 vellatle anthey',
 'A: Mari next time vellataaniki neeku avuthundha?',
 'A: Jrs tho',
 'B: Chance undha mam ani adiganu..kunukkunta annaru',
 'B: If unte chestha ledhante drop out eh',
 'A: Avna, c cirtificate voddha?',
 'B: Certificate akkarledh le experience chaalu',
 'A: 5% marks aanta, nuvvu aa govt exam raaaina?',
 "B: That's okay",
 'B:But 5% kosam ippudu stress thisko dhalchukoledhu',
 'A: Sarle, marks emivundhi le kastapadithe 100% kooda vasthaayi, ...',
 'B: Haa avnu',
 'A: Assalu stress theeskomaaku,Gudnyt, take care,Bye..',
 'B: Haa',
 'B: Good night',
 'B:Byee',
 'A: Mee question paper send chey',
 'A: So late,By now I solved half paper,...',
 'B: 🥲exam sarigga rayale so mummy tho matladuthu chudale',
 'B: Ok le anyway all theBest 👍',
 'A: No worries, idhi oka exam aa kaadhu naaku,...',
 'A: Vodhiley inka dhaanni,..',
 'B: Haa sare',
 '']

In [49]:
get_response(chat2)

> **Relationship:**
>
> The relationship between A and B is that of friends or classmates who are preparing for an exam together. They discuss exam preparation, exchange photos of charts and diagrams, and help each other out with practice questions.
>
> **A's Character:**
>
> A is a serious and responsible person who is focused on exam preparation. They are organized and efficient, and they like to have a plan. They are also helpful and willing to share their resources with others.
>
> **B's Character:**
>
> B is a more relaxed and easy-going person than A. They are also helpful and willing to share their resources, but they are not as focused on exam preparation as A. They are more interested in enjoying the process and having fun.
>
> **Analysis of the Conversation:**
>
> The conversation begins with A asking B if they have received a photo of a chart for the 9th exam. B replies that they have not, and A expresses disappointment. A then asks if B has any other charts, and B replies that they do have one. A requests B to send the chart so that they can practice, and B agrees.
>
> The conversation then turns to the upcoming exam camp, and A asks B if they are planning to attend. B replies that they are not, and A expresses disappointment. B explains that they have not received any information about the camp, but they will try to find out more.
>
> The conversation ends with A sending B a practice question and asking for their help in solving it. B agrees to help, and they wish each other good night.
>
> Overall, the conversation is friendly and cooperative, and it suggests that A and B have a good relationship.